version: 2.1

orbs:
  lumigo-orb: &lumigo_orb_version lumigo/lumigo-orb@volatile

defaults: &defaults
  working_directory: ~/lumigo-dotnet-tracer
  resource_class: small
  docker:
  - image: mcr.microsoft.com/dotnet/sdk:8.0

commands:
  checkout_code:
    description: "Checkout code and test it"
    steps:
      - checkout
      - run:
          # Avoid annoying double runs after deploy.
          # See https://discuss.circleci.com/t/job-runs-even-when-tags-ignore-filter-is-triggered-when-combined-with-branches-only/20664
          name: Stop deployment on tagged commits to avoid double-runs
          command: |
            tags=$(git tag -l --points-at HEAD)
            echo "Tags $tags"
            if [[ ! -z "$tags" ]]
            then
              echo "A tagged commit, skip..."
              circleci step halt
            fi
      - run: wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - run: dpkg -i packages-microsoft-prod.deb
      - run: apt-get update
      - run: apt-get install -y dotnet-sdk-8.0
      - run: apt install -y ssh
      - run:
          name: Clone utils repository
          command: |
            cd ..
            git clone git@github.com:lumigo-io/utils.git

            # attempt to checkout the matching branch if it exists
            cd utils
            git checkout "$CIRCLE_BRANCH" || true

workflows:
  test-deploy:
    jobs:
    - lumigo-orb/print_orb_versions:
        lumigo_orb_version: *lumigo_orb_version

    - lumigo-orb/test:
        context: 
          - common
          - nuget
        name: lumigo-orb/test
        docker_image: lumigo/python-39-ci:latest

    - lumigo-orb/is_environment_available:
        context: common
        filters:
          branches:
            ignore: master

    - lumigo-orb/be-deploy:
        context: common
        requires:
          - lumigo-orb/is_environment_available

    - lumigo-orb/prep-it-resources:
        context: 
          - common
          - nuget
        requires:
          - lumigo-orb/is_environment_available

    - lumigo-orb/integration-test-parallel:
        context: 
          - common
          - nuget
        run_test_cleanup: false
        requires:
          - lumigo-orb/be-deploy
          - lumigo-orb/prep-it-resources

    - lumigo-orb/e2e-test:
        context: common
        requires:
          - lumigo-orb/be-deploy
          - lumigo-orb/prep-it-resources

    - lumigo-orb/integration-test-cleanup:
        name: post-test-cleanup
        context: common
        requires:
          - lumigo-orb/integration-test-parallel
          - lumigo-orb/e2e-test

    - lumigo-orb/workflow-completed-successfully:
        context: common
        requires:
          - lumigo-orb/test
          - lumigo-orb/integration-test-parallel
          - lumigo-orb/e2e-test

    - deploy:
        context:
          - common
          - nuget
        filters:
          branches:
            only: master
        requires:
          - test

jobs:
  test:
    <<: *defaults
    steps:
      - checkout_code
      - run:
          name: run tests
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            ./scripts/checks.sh
            ./scripts/run_coverage.sh

  deploy:
    <<: *defaults
    resource_class: medium
    steps:
      - checkout_code
      - run: dotnet pack src/Lumigo.DotNET/ -c Release
      - run: ./scripts/bd_to_prod.sh
